import sys
import os
import asyncio
from dotenv import load_dotenv
from loguru import logger

# Add src to Python path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'src'))

from storm.core import StormSystem, StormConfig
from storm.models.llama_client import LlamaConfig
from storm.search.web_search import WebSearchManager, SerperSearchProvider

async def main():
    load_dotenv()
    logger.add("storm.log", rotation="10 MB")
    
    print("🌪️  STORM Article Generator")
    print("=" * 50)
    
    # Get user choice
    print("Choose generation mode:")
    print("1. Outline only (faster)")
    print("2. Full article (slower, more comprehensive)")
    
    try:
        choice = input("Enter choice (1 or 2): ").strip()
    except KeyboardInterrupt:
        print("\n👋 Goodbye!")
        return
    
    topic = input("Enter topic to research: ").strip()
    if not topic:
        topic = "Artificial Intelligence"
    
    print(f"\n🎯 Researching: {topic}")
    print("🔄 This may take a few minutes...")
    
    # Configuration
    llama_config = LlamaConfig(
        host=os.getenv("OLLAMA_HOST", "http://localhost:11434"),
        model=os.getenv("OLLAMA_MODEL", "llama3.2:latest")
    )
    
    storm_config = StormConfig(
        llama_config=llama_config,
        max_related_topics=4,
        max_perspectives=4,
        max_conversation_rounds=3,
        exclude_wikipedia=True
    )
    
    # Setup search
    serper_api_key = os.getenv("SERPER_API_KEY")
    if not serper_api_key:
        print("❌ Need SERPER_API_KEY in .env file")
        print("💡 Get free key from https://serper.dev")
        return
    
    search_provider = SerperSearchProvider(serper_api_key)
    search_manager = WebSearchManager(search_provider, ["en.wikipedia.org"])
    
    storm = StormSystem(storm_config, search_manager, topic)
    
    try:
        if choice == "2":
            # Full article generation
            print("📝 Generating full article...")
            outline, article, sources = await storm.generate_full_article(topic)
            
            print("\n" + "="*80)
            print(f"📄 FULL ARTICLE: {topic}")
            print("="*80)
            print(article)
            
            # Save to file
            filename = f"{topic.replace(' ', '_').replace('/', '_')}_article.md"
            with open(filename, 'w', encoding='utf-8') as f:
                f.write(f"# Research Report: {topic}\n\n")
                f.write(f"**Generated by STORM on:** {asyncio.get_event_loop().time()}\n\n")
                f.write("## Outline\n\n")
                f.write(outline)
                f.write("\n\n## Full Article\n\n")
                f.write(article)
                f.write(f"\n\n## Sources ({len(sources)})\n\n")
                for i, source in enumerate(sources, 1):
                    f.write(f"{i}. [{source.title}]({source.url})\n")
                    f.write(f"   {source.snippet[:200]}...\n\n")
            
            print(f"\n💾 Full article saved to: {filename}")
            
        else:
            # Outline only (original behavior)
            print("📋 Generating outline...")
            outline, sources = await storm.generate_article_outline(topic)
            
            print("\n" + "="*60)
            print(f"📋 OUTLINE: {topic}")
            print("="*60)
            print(outline)
        
        print(f"\n📚 Sources found: {len(sources)}")
        print("\nTop sources:")
        for i, source in enumerate(sources[:5], 1):
            print(f"{i}. {source.title[:60]}...")
            print(f"   🔗 {source.url}")
            
    except KeyboardInterrupt:
        print("\n⏹️  Generation stopped by user")
    except Exception as e:
        print(f"❌ Error: {e}")
        logger.error(f"STORM error: {e}")
        import traceback
        traceback.print_exc()

if __name__ == "__main__":
    asyncio.run(main())
