import sys
import os
import asyncio
from dotenv import load_dotenv
from loguru import logger
from datetime import datetime

# Add src to Python path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'src'))

from src.storm.core import StormSystem, StormConfig, UniversalStormSystem
from src.storm.models.llama_client import LlamaConfig
from src.storm.search.web_search import WebSearchManager, SerperSearchProvider

async def main():
    load_dotenv()
    logger.add("storm.log", rotation="10 MB")
    
    print("🌪️  STORM Article Generator")
    print("=" * 50)
    
    # Get user choice
    print("Choose generation mode:")
    print("1. Outline only (faster)")
    print("2. Full article (slower, more comprehensive)")
    
    try:
        choice = input("Enter choice (1 or 2): ").strip()
    except KeyboardInterrupt:
        print("\n👋 Goodbye!")
        return
    
    topic = input("Enter topic to research: ").strip()
    if not topic:
        topic = "Artificial Intelligence"
    
    print(f"\n🎯 Researching: {topic}")
    print("🔄 This may take a few minutes...")
    
    # Configuration
    llama_config = LlamaConfig(
        host=os.getenv("OLLAMA_HOST", "http://localhost:11434"),
        model=os.getenv("OLLAMA_MODEL", "llama3.2:latest")
    )
    
    storm_config = StormConfig(
        llama_config=llama_config,
        max_related_topics=4,
        max_perspectives=4,
        max_conversation_rounds=3,
        exclude_wikipedia=True
    )
    
    # Setup search
    serper_api_key = os.getenv("SERPER_API_KEY")
    if not serper_api_key:
        print("❌ Need SERPER_API_KEY in .env file")
        print("💡 Get free key from https://serper.dev")
        return
    
    search_provider = SerperSearchProvider(serper_api_key)
    
    # Simple search manager without LLM filtering (temporarily)
    search_manager = WebSearchManager(
        provider=search_provider, 
        exclude_domains=["en.wikipedia.org"]
        # Removed llm_client temporarily until we fix the filtering
    )
    
    # Use Universal system instead of complex STORM
    universal_storm = UniversalStormSystem(
        config=storm_config,
        search_manager=search_manager,
        target_topic=topic
    )    
    
    try:
        if choice == "2":
            # Full article generation
            print("📝 Generating article with dynamic search...")
            outline, article, sources = await universal_storm.generate_universal_article(topic)
            
            print("\n" + "="*80)
            print(f"📄 FULL ARTICLE: {topic}")
            print("="*80)
            print(article)
            
            # Save to file
            filename = f"{topic.replace(' ', '_').replace('/', '_')}_article.md"
            timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            
            with open(filename, 'w', encoding='utf-8') as f:
                f.write(f"# Research Report: {topic}\n\n")
                f.write(f"**Generated by STORM on:** {timestamp}\n\n")
                f.write("## Outline\n\n")
                f.write(outline)
                f.write("\n\n## Full Article\n\n")
                f.write(article)
                
                # FIXED: Better source formatting with error handling
                f.write(f"\n\n## Sources ({len(sources)})\n\n")
                if sources:
                    for i, source in enumerate(sources, 1):
                        try:
                            # Get title safely
                            title = getattr(source, 'title', 'No title')
                            if not title or title.strip() == '':
                                title = 'No title'
                            
                            # Get URL safely  
                            url = getattr(source, 'url', '#')
                            if not url or url.strip() == '':
                                url = '#'
                            
                            # Get snippet safely
                            snippet = getattr(source, 'snippet', '')
                            if not snippet:
                                snippet = getattr(source, 'content', '')
                            if not snippet:
                                snippet = "No description available"
                            
                            # Truncate snippet
                            snippet_preview = snippet[:200] if len(snippet) > 200 else snippet
                            if len(snippet) > 200:
                                snippet_preview += "..."
                            
                            # Write source entry
                            f.write(f"{i}. [{title}]({url})\n")
                            f.write(f"   {snippet_preview}\n\n")
                            
                        except Exception as e:
                            logger.warning(f"Error formatting source {i}: {e}")
                            f.write(f"{i}. Source {i}\n")
                            f.write(f"   Error displaying source details\n\n")
                else:
                    f.write("No sources found.\n\n")
            
            print(f"\n💾 Full article saved to: {filename}")
            
        else:
            # Outline only (original behavior)
            print("📋 Generating outline...")
            outline, article, sources = await universal_storm.generate_universal_article(topic)
            
            print("\n" + "="*60)
            print(f"📋 OUTLINE: {topic}")
            print("="*60)
            print(outline)
        
        print(f"\n📚 Sources found: {len(sources)}")
        print("\nTop sources:")
        for i, source in enumerate(sources[:5], 1):
            try:
                title = getattr(source, 'title', 'No title')
                url = getattr(source, 'url', 'No URL')
                
                # Truncate title for display
                display_title = title[:60] if len(title) > 60 else title
                if len(title) > 60:
                    display_title += "..."
                
                print(f"{i}. {display_title}")
                print(f"   🔗 {url}")
            except Exception as e:
                logger.warning(f"Error displaying source {i}: {e}")
                print(f"{i}. Source {i} (error displaying details)")
                
    except KeyboardInterrupt:
        print("\n⏹️  Generation stopped by user")
    except Exception as e:
        print(f"❌ Error: {e}")
        logger.error(f"STORM error: {e}")
        import traceback
        traceback.print_exc()

if __name__ == "__main__":
    asyncio.run(main())